export enum Role {
  ADMIN = 'ADMIN',
  COMMERCIAL = 'COMMERCIAL',
  TRANSPORTEUR = 'TRANSPORTEUR',
  OPERATEUR = 'OPERATEUR',
  FOURNISSEUR = 'FOURNISSEUR',
}

export enum UserType {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
}
